name: Deploy to VPS

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: deepsearch
    steps:
      - uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake gcc

      - name: Debug Information
        run: |
          echo "Debugging connection to VPS..."
          echo "VPS_HOST: ${{ secrets.VPS_HOST }}"
          echo "VPS_USERNAME: ${{ secrets.VPS_USERNAME }}"

      - name: Copy files to VPS
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          source: "."
          target: "/home/ubuntu/deepsearch"
          debug: true

      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            echo "Current directory: $PWD"
            cd /home/ubuntu/deepsearch
            docker build -t agent-serp-worker .
            docker stop deepserper || true
            docker rm deepserper || true
            docker run -d --name deepserper \
              --restart unless-stopped \
              -e NOTION_API_KEY="${{ secrets.NOTION_API_KEY }}" \
              -e NOTION_DATABASE_ID="${{ secrets.NOTION_DATABASE_ID }}" \
              -e OPENROUTER_API_KEY="${{ secrets.OPENROUTER_API_KEY }}" \
              -e OPENROUTER_BASE_URL="${{ secrets.OPENROUTER_BASE_URL }}" \
              -e SEEDREAM="${{ secrets.SEEDREAM }}" \
              -e DREAMINA="${{ secrets.DREAMINA }}" \
              -e GROK_API_KEY="${{ secrets.GROK_API_KEY }}" \
              -e GROK3API="${{ secrets.GROK3API }}" \
              -e DAILY_TIME="${{ secrets.DAILY_TIME }}" \
              -e DISCORD_WEBHOOK_ID="${{ secrets.DISCORD_WEBHOOK_ID }}" \
              -e TELEGRAM_BOT_TOKEN="${{ secrets.TELEGRAM_BOT_TOKEN }}" \
              -e TELEGRAM_CHAT_ID="${{ secrets.TELEGRAM_CHAT_ID }}" \
              agent-serp-worker