name: Deploy to VPS

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: deepsearch
    steps:
      - uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake gcc

      - name: Debug Information
        run: |
          echo "Debugging connection to VPS..."
          echo "VPS_HOST: ${{ secrets.VPS_HOST }}"
          echo "VPS_USERNAME: ${{ secrets.VPS_USERNAME }}"

      - name: Copy files to VPS
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          source: "."
          target: "/home/ubuntu/deepsearch"
          debug: true

      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            echo "Current directory: $PWD"
            cd /home/ubuntu/deepsearch
            docker build -t agent-serp-worker .
            docker stop deepserper || true
            docker rm deepserper || true
            docker run -d --name deepserper --network host \
              -e AIRTABLE_KEY="${{ secrets.AIRTABLE_KEY }}" \
              -e AIRTABLE_BASE_ID="${{ secrets.AIRTABLE_BASE_ID }}" \
              -v /home/ubuntu/chromium-xvbf/browser-data:/browser-data \
              agent-serp-worker